# encoding: UTF-8

import pathlib
import re


def main():
    solutions = []
    root_dir = pathlib.Path(__file__).parent.parent / "solutions"
    for solution_file in root_dir.glob("*.cpp"):
        match = re.match(r"^(\d{4})-.*\.cpp$", solution_file.name)
        if match:
            solutions.append(solution_file)
    solutions.sort()
    cmake_begin = f"""# GENERATED BY 'scripts/gen.py', DO NOT EDIT MANUALLY

add_library(solution-objs OBJECT
"""
    cmake_end = f"""
)

target_link_libraries(solution-objs PUBLIC leetcode compile-options)
"""
    cmake_content = "\n".join(f"  {solution.name}" for solution in solutions)
    with open(root_dir / "CMakeLists.txt", "w") as f:
        f.write(cmake_begin)
        f.write(cmake_content)
        f.write(cmake_end)

if __name__ == "__main__":
    main()
