# encoding: UTF-8

import os
import re


def main():
    solutions = []
    for filename in os.listdir('src'):
        m = re.match(r'^(\d+)\.(.+)\.cpp$', filename)
        if m is not None:
            serial, name = m.groups()
            solutions.append((int(serial), name, filename))
    solutions.sort(key=lambda t: t[0])
    with open('cmake/solutions.cmake', 'w') as fd:
        fd.write('# DONT EDIT: THIS FILE IS GENERATED BY scripts/gen.py\n\n')
        fd.writelines(
            [f'add_solution({serial:04d} src/{cpp:s})\n' for serial, _, cpp in solutions])


if __name__ == "__main__":
    main()
